apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-envdisplay
  namespace: akv2k8s-ns
  labels:
    app: envdisplay-app
spec:
  selector:
    matchLabels:
      app: envdisplay-app
  template:
    metadata:
      labels:
        app: envdisplay-app
    spec:
      containers:
      - name: envdisplay-app-pod
        image: iamraj007/printenv:output
        args: ["PRINT_SYNC_SECRET"]
        env:
        - name: PRINT_SYNC_SECRET
          value: "akv-vault-injection-sync@azurekeyvault" 

